export const premiumTheme = {
  colors: {
    background: "#fbf6ef",
    surface: "#fffdfa",
    surfaceMuted: "#f8efe4",
    surfaceRaised: "#fffaf4",
    border: "#eadfd2",
    borderStrong: "#d8c7b4",
    text: "#2d241d",
    textSoft: "#7d6d5d",
    textMuted: "#a39384",
    accent: "#3a2d23",
    accentSoft: "#efe1d1",
    accentWarm: "#a7744d",
    successBg: "#eef8ef",
    successText: "#4d9b5b",
    warningBg: "#fff4e8",
    warningText: "#b87a35",
    dangerBg: "#fff0ef",
    dangerText: "#cf6c63",
  },
  radius: {
    sm: 12,
    md: 18,
    lg: 24,
    xl: 30,
    pill: 999,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
    xxl: 30,
  },
  shadow: {
    card: {
      shadowColor: "#2a1e14",
      shadowOpacity: 0.06,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    floating: {
      shadowColor: "#2a1e14",
      shadowOpacity: 0.12,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
      elevation: 6,
    },
  },
} as const;

