export const premiumTheme = {
  colors: {
    background: "#fff8f1",
    surface: "#ffffff",
    surfaceMuted: "#fff1e1",
    surfaceRaised: "#fff9f3",
    border: "#ead8c5",
    borderStrong: "#d7bfa8",
    text: "#2d241d",
    textSoft: "#786453",
    textMuted: "#a38974",
    accent: "#3a2d23",
    accentSoft: "#f6e4d2",
    accentWarm: "#cf8649",
    successBg: "#ebfaef",
    successText: "#2f9d61",
    warningBg: "#fff3df",
    warningText: "#c87a23",
    dangerBg: "#fff0ec",
    dangerText: "#d45f57",
  },
  radius: {
    sm: 12,
    md: 18,
    lg: 24,
    xl: 30,
    pill: 999,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
    xxl: 30,
  },
  shadow: {
    card: {
      shadowColor: "#2a1e14",
      shadowOpacity: 0.06,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    floating: {
      shadowColor: "#2a1e14",
      shadowOpacity: 0.12,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
      elevation: 6,
    },
  },
} as const;
